# 运行环境，Travis 会自动提供这个环境
language: node_js
node_js:
  - 10
# node_js: stable
cache: npm
git:
  depth: 1
  submodules: true

# S: Build Lifecycle
before_install:
- npm install hexo-cli -g
# 安装依赖包
install:
  - npm install

# 生成博客静态资源
script:
  - hexo clean
  - hexo g

# 将静态资源推送到 master 分支上
after_script:
  # 找到静态资源
  - cd ./public
  - git init
  # user.name 和 user.email 让 travis 能登录你的 github
  - git config user.name "davisjy"
  - git config user.email "Davis_jy@163.com"
  - hexo deploy
  #- git add .
  #- git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  # GH_REF 告诉 travis 往哪个仓库推送代码，具体值下面配置
  #- git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    # 设置监控分支，当 dev 分支代码变化时，执行这个程序
    - dev
env:
  global:
    # 定义往哪个仓库推送代码，注意事项见下面
    - GH_REF: github.com/Davisjy/Davisjy.github.io.git